### ISSUE TITLE
SCP-008 and SCP-049 separated

### ISSUE THREAD

**Issue by Redd-king** [Rnen/SCP008#1]
If an SCP-049 spawns, he can create SCP-008 by infecting people. They then get to infect other people and so on and so forth. Instead, it should be either 049 or 008 every other round. If 049 spawns, then the game will go as if 008 wasn’t on the server. If an 049 doesn’t spawn, a random D-class is infected on the start of the round and will be designated as patient zero. Patient zero can’t cure the infection with a med kit, but can be shot before he gets fully infected.

**Comment by Rnen** [comment]
# Addendum from another player:
* Allowing for a config option to spawn a certain amount of 049-2 zombies along with the plague doctor would be amazing.

**Comment by Rnen** [comment]
Not sure if i'll ever get around to do this, it's a pain to do :pensive:
