### ISSUE TITLE
PLugin is not loading

### ISSUE THREAD

**Issue by Nikitonz** [Rnen/SCP008#18]
![image](https://github.com/Rnen/SCPSL-SCP008/assets/100299461/6f8432c9-aac3-4cb0-ad8b-5d55993ea065)
Seems plugin is outdated, needs to be fixed

**Comment by Rnen** [comment]
@Nikitonz What SMod Version was this?

**Comment by Nikitonz** [comment]
Latest available on Steam Secret Laboratory Server Mod (app id: 786920)

**Comment by Nikitonz** [comment]
seems like this version is deprecated, so we can close this thread(anyway, server mod doesn't works)
