### ISSUE TITLE
Possible Linux Issue

### ISSUE THREAD

**Issue by 017** [Rnen/SCP008#4]
Tried running this on my linux setup, but it produces a lot of error spam in console and doesn't function outside of the commands for admins seeming to have registered properly.

Here's the console error - maybe it's related to capitalization issues or something, cause the SCP version is correct and nobody else seems to be having this problem.
> [01:36:30] [01:36:30] [ERROR] [Event]    at System.Collections.Generic.List`1[Smod2.API.Player].ForEach (System.Action`1 action) [0x00000] in <filename unknown>:0 
>   at SCP008PLUGIN.EventHandlers.OnUpdate (Smod2.Events.UpdateEvent ev) [0x00000] in <filename unknown>:0 
>   at Smod2.Events.UpdateEvent.ExecuteHandler (IEventHandler handler) [0x00000] in <filename unknown>:0 
>   at Smod2.Events.EventManager.HandleEvent[IEventHandlerUpdate] (Smod2.Events.Event ev) [0x00000] in <filename unknown>:0 
> 
> [01:36:33] [01:36:33] [ERROR] [Event]  Event Handler: SCP008PLUGIN.EventHandlers Failed to handle event:Smod2.Events.UpdateEvent

**Comment by Rnen** [comment]
Interesting :thinking: 
Are you sure this was the correct release for your smod version?
